#ifndef ENUMS_H_INCLUDED
#define ENUMS_H_INCLUDED

namespace my {

enum SortDirection {
    SORTDIRECTION_ASC,
    SORTDIRECTION_DESC,
    SORTDIRECTION_NONE
};

enum TableDataChange {
	TABLEDATA_ROW_ADDED,
	TABLEDATA_COLUMN_ADDED,
	TABLEDATA_ROW_REMOVED,
	TABLEDATA_COLUMN_REMOVED,
	TABLEDATA_ALL_ROWS_REMOVED,
	TABLEDATA_CLEARED,
	TABLEDATA_CHANGED,
	TABLEDATA_VALUE_CHANGED,
	TABLEDATA_SORTED
};

}

#endif // ENUMS_H_INCLUDED
